const { withAppDelegate, withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const XCODE_ENV_LOCAL = `# Auto-generated by withNativeIosStandalone — do not edit; change plugins/native-ios templates instead.
# Xcode (Dock) has no nvm/node in PATH:
if [ -z "$NODE_BINARY" ] || [ ! -x "$NODE_BINARY" ]; then
  if [ -x /opt/homebrew/bin/node ]; then
    export NODE_BINARY=/opt/homebrew/bin/node
  elif [ -x /usr/local/bin/node ]; then
    export NODE_BINARY=/usr/local/bin/node
  elif [ -n "$HOME" ] && [ -d "$HOME/.nvm/versions/node" ]; then
    NVM_VER=$(ls -1 "$HOME/.nvm/versions/node" 2>/dev/null | sort -V | tail -n 1)
    if [ -n "$NVM_VER" ] && [ -x "$HOME/.nvm/versions/node/$NVM_VER/bin/node" ]; then
      export NODE_BINARY="$HOME/.nvm/versions/node/$NVM_VER/bin/node"
    fi
  fi
fi
# Always embed JS at build time. SKIP_BUNDLING=0 is still truthy in bash — must unset.
unset SKIP_BUNDLING
export SKIP_BUNDLING_METRO_IP=1
export CONFIGURATION=Release
`;

const XCODE_ENV_UPDATES = `# Auto-generated — cancels Expo Debug SKIP_BUNDLING=1 override
unset SKIP_BUNDLING
`;

const DEBUG_SKIP_BLOCK =
  'if [[ \\"$CONFIGURATION\\" = *Debug* ]]; then\\n  export SKIP_BUNDLING=1\\nfi\\n';

/**
 * iOS always ships with embedded main.jsbundle — no Metro, no Expo Go, App Store ready.
 * - AppDelegate: never loads from dev server
 * - Xcode: always runs export:embed (Debug + Release)
 * - EAS prebuild: writes xcode env without manual apply-native-ios
 */
function withNativeIosStandalone(config) {
  config = withAppDelegate(config, (cfg) => {
    let contents = cfg.modResults.contents;

    const sourcePattern = /override func sourceURL\(for bridge: RCTBridge\) -> URL\? \{[\s\S]*?\n  \}/;
    if (!sourcePattern.test(contents)) {
      throw new Error('withNativeIosStandalone: sourceURL(for:) not found in AppDelegate');
    }
    contents = contents.replace(
      sourcePattern,
      `override func sourceURL(for bridge: RCTBridge) -> URL? {
    bundleURL()
  }`,
    );

    const bundlePattern = /override func bundleURL\(\) -> URL\? \{[\s\S]*?\n  \}/;
    if (!bundlePattern.test(contents)) {
      throw new Error('withNativeIosStandalone: bundleURL() not found in AppDelegate');
    }
    contents = contents.replace(
      bundlePattern,
      `override func bundleURL() -> URL? {
    return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
  }`,
    );

    cfg.modResults.contents = contents;
    return cfg;
  });

  config = withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const iosRoot = cfg.modRequest.platformProjectRoot;

      fs.writeFileSync(path.join(iosRoot, '.xcode.env.local'), XCODE_ENV_LOCAL);
      fs.writeFileSync(path.join(iosRoot, '.xcode.env.updates'), XCODE_ENV_UPDATES);

      const pbxName = fs.readdirSync(iosRoot).find((f) => f.endsWith('.xcodeproj'));
      if (pbxName) {
        const pbxPath = path.join(iosRoot, pbxName, 'project.pbxproj');
        if (fs.existsSync(pbxPath)) {
          let pbx = fs.readFileSync(pbxPath, 'utf8');
          if (pbx.includes(DEBUG_SKIP_BLOCK)) {
            pbx = pbx.replace(DEBUG_SKIP_BLOCK, '');
          }
          pbx = pbx.replace(/IPHONEOS_DEPLOYMENT_TARGET = 1[56]\.\d;/g, 'IPHONEOS_DEPLOYMENT_TARGET = 15.1;');
          fs.writeFileSync(pbxPath, pbx);
        }
      }

      const schemePath = pbxName
        ? path.join(
            iosRoot,
            pbxName,
            'xcshareddata',
            'xcschemes',
            `${pbxName.replace(/\.xcodeproj$/, '')}.xcscheme`,
          )
        : null;
      if (schemePath && fs.existsSync(schemePath)) {
        let scheme = fs.readFileSync(schemePath, 'utf8');
        scheme = scheme.replace(
          /<LaunchAction([^>]*)\n\s+buildConfiguration = "Debug"/,
          '<LaunchAction$1\n      buildConfiguration = "Release"',
        );
        fs.writeFileSync(schemePath, scheme);
      }

      const propsPath = path.join(iosRoot, 'Podfile.properties.json');
      if (fs.existsSync(propsPath)) {
        const props = JSON.parse(fs.readFileSync(propsPath, 'utf8'));
        props['ios.deploymentTarget'] = '15.1';
        props.EX_DEV_CLIENT_NETWORK_INSPECTOR = 'false';
        fs.writeFileSync(propsPath, `${JSON.stringify(props, null, 2)}\n`);
      }

      return cfg;
    },
  ]);

  return config;
}

module.exports = withNativeIosStandalone;
